name: Cypress E2E

on: [push]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Cypress run
        working-directory: ./builder_website
        uses: cypress-io/github-action@v6
        with:
          build: npm run build
          start: npm start
      - name: Upload generated JSON files
        uses: actions/upload-artifact@v4
        with:
          name: cypress-artifacts
          path: path/to/
          if-no-files-found: error

  plugin-jar-gen:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Generate Jar for validation only
        working-directory: plugin
        run: mvn -DskipTests=true clean compile package -P e2e
      - name: Upload jar
        uses: actions/upload-artifact@v4
        with:
          name: Plugin JAR Artifacts
          path: plugin/generated_jar/PluginValidation.jar
          if-no-files-found: error

  plugin-validation:
    needs: [cypress-run, plugin-jar-gen]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Download JSON Artifacts and Plugin Validation JAR
        uses: actions/download-artifact@v4
      - name: Display
        run: ls -R
      - name: Perform validation
        run: java -jar generated_jar/PluginValidation.jar path/to
      - name: Upload validation results
        uses: actions/upload-artifact@v4
        with:
          name: Plugin Validation Results
          path: generated_jar/results.json
          if-no-files-found: error
  