name: Plugin Unit and Integration Tests

on:
  push:
    paths:
      - 'plugin/**'
    paths-ignore:
      - 'docs/**'
jobs:
  unit-tests:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
      checks: write
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'adopt'
      - name: Run Unit Tests
        working-directory: plugin
        run: mvn clean test-compile -B test -P plugin
        
      - name: Report Unit Tests
        uses: dorny/test-reporter@v1
        if: always()
        with:
          name: Maven Tests
          path : plugin/target/surefire-reports/*.xml
          reporter: java-junit
          fail-on-error: true
  integration-tests:
    needs: [unit-tests]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
    
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'adopt'
      - name: Run Integration Tests
        working-directory: plugin
        run: mvn clean test-compile failsafe:integration-test failsafe:verify -P plugin -Dstage=testing
      - name: Report Integration Tests
        uses: dorny/test-reporter@v1
        if: always()
        with:
          name: Maven Tests
          path : plugin/target/failsafe-reports/*.xml
          reporter: java-junit
          fail-on-error: true

